### PR TITLE
New Language Neutral Test Suite (redux)

### PR DESCRIPTION
**Pull request by xogeny**
(resubmitting this, something went wrong with the other branch)

The majority of test cases have been refactored from Javascript code into a canonical test case form and stored as JSON.  This change makes it very easy for other implementation written in other languages to test compliance with `jsonata`.  It also helps organize the tests into categories.

Included in this commit is a markdown file documenting the data files present in the new test suite. 
 Also included is a mocha test that executes all of the tests by looping over all the provided test case data.

It is important to emphasize that no tests were removed.  They were only refactored into language neutral versions and a few lingering implementation specific versions.  Furthermore, these changes **preserve the current code coverage at 100% across the board**.

Signed-off-by: Michael M. Tiller \<michael.tiller@gmail.com\>

### CODE REVIEW

**Comment by xogeny** [comment]
OK, I updated this pull requests rebasing it off of the `singleton` branch **and** improving the structure of the test suite data (IMHO).

All tests pass (including the new tests added on the `singleton` branch) and we still have 100% coverage.

Interestingly, no new tests were actually needed to get 100% test cases, just updated answers...but I added the new tests all the same.

**Comment by xogeny** [comment]
This replaces PR #113, BTW.

**Comment by andrew-coleman** [comment]
@xogeny many thanks for contributing this change.  This was a huge piece of work and as a result we have a really well structured test suite that can be used by multiple implementations.
Thanks again!

**Comment by mattbaileyuk** [comment]
@xogeny I want to second @andrew-coleman; it was a big piece of work and a big step forward - many thanks!

**Comment by xogeny** [comment]
@andrew-coleman @mattbaileyuk Happy to help.  You've created a very compelling approach here so I can't help but want to see it move forward. I've got some other ideas for PRs. Hopefully you'll find those useful as well.

**Pull request merged**
