### PR TITLE
Fix binding operation evaluation in objects

### PR DESCRIPTION
**Pull request by asennikov**
The issue was originally raised here: https://stackoverflow.com/questions/77742737/jsonata-transform-operator-unexpected-change-in-variable-binding-between-versi

Before https://github.com/jsonata-js/jsonata/pull/583 a JSONata user could bind a variable within an RHS expression of one of the object entries and then reuse that variable within another object entry, e.g.:

```
{ 
    "foo": $bar := "x",
    "bar": $bar
}
```

Here's the result on 1.8.6:

image

But due to the `await Promise.all` added in https://github.com/jsonata-js/jsonata/pull/583, this no longer works in 2.0.3:

image

----------
 
In this PR, I'm proposing a change to remove the `Promise.all` and iterate sequentially, which might have some performance implications for certain users of JSONata, but IMO, it would still be better to maintain compatibility between versions.

All tests are passing:

image

### CODE REVIEW

**Review by efhjones — APPROVED** [review]
👍 Seems reasonable to me

**Review by scarabaeus — APPROVED** [review]
Thanks for the fast turn-around on this @asennikov!

**Comment by VesaliaBricks** [comment]
As the originator on SO, thank you for clearing that up. Will try to re-formulate my business logic.
Bit frustrating, but I still love JSONata,
Sebastian

**Comment by asennikov** [comment]
> Sorry, no.  There is no guaranteed order of execution of expressions within an object (`{...}`).  Although this Javascript implementation executes them in the same order as appears in the expression, other implementations (such as `go`) don't necessarily. See https://github.com/jsonata-js/jsonata/issues/179 for example.
> The only construct in JSONata that guarantees order of execution is the block `(... ; ... ; ...)` expression.

Sounds reasonable.

**Pull request closed without merging**
