### PR TITLE
Add support for comments in expression

### LINKED ISSUE #75: Support for embedded comments within expressions
During discussion of [another issue](https://github.com/jsonata-js/jsonata/issues/70#issuecomment-326428722), it became clear there is a desire to be able to embed comments within multiline expressions.

Options discussed included aligning with other scripting languages that use `#` to indicate the start of a comment, or Javascript/Java/C that use `//` or `/* ... */` for comments.

This issue can be used to host any further discussion on this requirement.

### PR DESCRIPTION
**Pull request by andrew-coleman**
resolves #75

### CODE REVIEW

**Comment by jhorbulyk** [comment]
Is there going to be a corresponding PR for the documentation?

**Comment by mattbaileyuk** [comment]
@jhorbulyk Very good point, although we'd probably want to make the change around the time this change gets published to npm. I've created an issue on the documentation repo to remind us: https://github.com/jsonata-js/jsonata-js.github.io/issues/12

**Comment by janvda** [comment]
What is the chosen syntax for comments ?  Is it **/* */** or **//** or both or something else ?

**Comment by mattbaileyuk** [comment]
@janvda Sorry, missed your comment until now; the syntax is that comments must start with a `/*` and end with a `*/`; if the latter is missing then an error is thrown. Hope to get this properly written up into the (new) docs soon now that JSONata 1.6.x is live with this functionality.

**Pull request merged**
